"""A saved run's framework references are never rewritten by a later build.

The corpus this reads is a real document, written by `guardana scan` running the
released 0.12.0 code, kept byte for byte. That is the point: a hand-written fixture
would only prove that this build agrees with what this build's author believed 0.12
wrote, and the field that matters here — a `LLM07` recorded under `OWASP-LLM-2025`
while the installed 2026 edition gives that id to Misinformation — is exactly the
kind of detail such a belief gets wrong.

1.0 entry criterion 4 is the reason this directory exists: every supported build
reads and correctly `diff`s the whole saved-run corpus from 0.12 onward, including
runs whose taxonomy references collide across editions.
"""

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest
from guardana.core.diff import compare_reports
from guardana.core.diff.compare import finding_identity
from guardana.core.manifest import MANIFEST_SCHEMA_VERSION
from guardana.core.manifest.load import ManifestLoadError
from guardana.core.manifest.serialize import SCHEMA_URL
from guardana.core.report import Finding, load_report
from guardana.core.report.load import migrate_forward
from guardana.core.report.run import REPORT_SCHEMA_VERSION
from guardana.core.taxonomy import resolve

_CORPUS = Path(__file__).parent / "saved_runs"
_RUN_012 = _CORPUS / "run-0.12.0-artifact-scan.json"


def _document() -> dict[str, Any]:
    loaded: dict[str, Any] = json.loads(_RUN_012.read_text(encoding="utf-8"))
    return loaded


def test_the_corpus_is_what_it_claims_to_be() -> None:
    # Guards the guard: a fixture quietly regenerated by a later build would make
    # every test below pass while proving nothing about backwards compatibility.
    document = _document()

    assert document["schema_version"] == 2
    assert document["run"]["guardana"]["version"] == "0.12.0"
    assert {"framework": "OWASP-LLM-2025", "id": "LLM03"} in document["findings"][0]["taxonomy"]


def test_a_2025_reference_in_a_0_12_run_still_reads_as_the_2025_edition() -> None:
    # The whole defect this release repairs, seen from the reader's side. In the
    # 2025 edition LLM03 is Supply Chain; in the 2026 edition it is Excessive
    # Agency. Reading the stored id without its framework would file a pickle
    # finding under an agentic control.
    report = load_report(_RUN_012)

    references = {
        (ref.framework, ref.id, ref.title)
        for finding in report.result.findings
        for ref in finding.taxonomy
    }

    assert ("OWASP-LLM-2025", "LLM03", "Supply Chain") in references
    assert not any(framework == "OWASP-LLM-2026" for framework, _id, _title in references)


def test_the_installed_2026_edition_disagrees_with_that_id_and_is_not_consulted() -> None:
    # Stated as its own assertion so the test above cannot pass by coincidence on a
    # build where the two editions happen to agree.
    twenty_six = resolve("LLM03:2026")

    assert twenty_six is not None
    assert twenty_six.title == "Excessive Agency"
    assert resolve("LLM03:2025") is not None
    assert resolve("LLM03:2025").title == "Supply Chain"  # type: ignore[union-attr]


def test_migration_recovers_the_title_without_touching_the_reference() -> None:
    migrated = migrate_forward(_document(), 2)

    assert migrated["schema_version"] == REPORT_SCHEMA_VERSION
    recorded = migrated["findings"][0]["taxonomy"]
    assert {"framework": "OWASP-LLM-2025", "id": "LLM03", "title": "Supply Chain"} in recorded
    # Nothing invented where nothing is known, and nothing remapped.
    assert all(entry["framework"] != "OWASP-LLM-2026" for entry in recorded)


def test_a_migrated_document_stops_claiming_the_older_contract() -> None:
    # `$schema` names the contract a consumer is holding before it parses anything.
    # Carrying version 2's identifier into a version-3 file would tell them they
    # have a document they do not — and `run migrate` writes this file to disk, so
    # the wrong identifier travels with the evidence.
    document = _document()
    assert "v2.schema.json" in document["$schema"]

    migrated = migrate_forward(document, 2)

    assert migrated["$schema"] == SCHEMA_URL
    assert f"v{MANIFEST_SCHEMA_VERSION}" in SCHEMA_URL


def test_a_malformed_taxonomy_is_refused_by_the_migration_not_quietly_emptied() -> None:
    # The reader raises on a taxonomy that is not a list. A migration that rewrote
    # one to `[]` would slip past that check by fixing the document first, and the
    # evidence would come back with its mapping silently gone.
    document = _document()
    document["findings"][0]["taxonomy"] = "LLM03"

    with pytest.raises(ManifestLoadError, match="'taxonomy' must be a list"):
        migrate_forward(document, 2)


def test_migration_leaves_an_unknown_framework_titleless_rather_than_guessing() -> None:
    document = _document()
    document["findings"][0]["taxonomy"] = [{"framework": "ACME-CONTROLS-1", "id": "ACME-14"}]

    migrated = migrate_forward(document, 2)

    assert migrated["findings"][0]["taxonomy"] == [
        {"framework": "ACME-CONTROLS-1", "id": "ACME-14", "title": ""}
    ]


def test_a_0_12_run_diffs_against_one_this_build_wrote(tmp_path: Path) -> None:
    before = load_report(_RUN_012)
    after = load_report(_rewritten_later(tmp_path, _document()))

    diff = compare_reports(before, after)

    assert diff.changes == ()
    assert diff.unchanged > 0
    assert any("coverage fingerprint" in note for note in diff.notes), (
        "a run with no fingerprint must be reported as unknown reach, never as equal reach"
    )


def test_remapping_a_rule_does_not_move_a_findings_identity() -> None:
    """A waiver in a baseline, and a triage decision in the collector, hang off this.

    `finding_identity` is `(rule_id, location)` and taxonomy is not in it. If a
    framework remap could change it, this release would silently un-waive every
    accepted finding a team is carrying.
    """
    report = load_report(_RUN_012)
    finding = report.result.findings[0]
    root = report.manifest.target.ref

    remapped = Finding(
        rule_id=finding.rule_id,
        severity=finding.severity,
        title=finding.title,
        taxonomy=(resolve("LLM06:2026"),),  # type: ignore[arg-type]
        target_ref=finding.target_ref,
        evidence=finding.evidence,
        verdict=finding.verdict,
    )

    assert finding_identity(remapped, root) == finding_identity(finding, root)


def _rewritten_later(tmp_path: Path, document: dict[str, Any]) -> Path:
    """The same run, migrated forward and stamped later, standing in for a re-run.

    Built from the corpus rather than by scanning, so the comparison isolates one
    variable: two documents that describe the same findings at two schema versions
    must diff as unchanged.
    """
    migrated = migrate_forward(document, 2)
    later = datetime(2026, 12, 1, tzinfo=UTC).isoformat().replace("+00:00", "Z")
    migrated["run"] = {**migrated["run"], "started_at": later, "created_at": later}
    path = tmp_path / "later.json"
    path.write_text(json.dumps(migrated), encoding="utf-8")
    return path


@pytest.fixture(autouse=True)
def _corpus_exists() -> None:
    assert _RUN_012.is_file(), f"the saved-run corpus is missing {_RUN_012.name}"
