"""Curated allowlist of common top-level import names for well-known PyPI distributions.

Used by HallucinatedPackageRule to reduce false positives: this is not an
exhaustive PyPI mirror, just the popular ML/data/web packages a Guardana
target is likely to legitimately depend on.
"""

KNOWN_DISTRIBUTIONS: frozenset[str] = frozenset(
    {
        "torch",
        "torchvision",
        "torchaudio",
        "numpy",
        "pandas",
        "scipy",
        "sklearn",
        "transformers",
        "datasets",
        "tokenizers",
        "accelerate",
        "diffusers",
        "huggingface_hub",
        "sentencepiece",
        "safetensors",
        "onnx",
        "onnxruntime",
        "tensorflow",
        "keras",
        "jax",
        "jaxlib",
        "flax",
        "requests",
        "httpx",
        "urllib3",
        "aiohttp",
        "yaml",
        "toml",
        "pydantic",
        "fastapi",
        "starlette",
        "uvicorn",
        "flask",
        "django",
        "click",
        "typer",
        "rich",
        "tqdm",
        "attrs",
        "packaging",
        "setuptools",
        "wheel",
        "pytest",
        "boto3",
        "botocore",
        "sqlalchemy",
        "redis",
        "pillow",
        "PIL",
        "matplotlib",
        "seaborn",
        "networkx",
        "nltk",
        "spacy",
        "gensim",
        "openai",
        "anthropic",
        "langchain",
        "llama_index",
        "dotenv",
        "jinja2",
        "cryptography",
        "jsonschema",
        "defusedxml",
    }
)
