"""Generate the factual documentation fragments from the installed registry.

Every count this project states in prose has drifted at least once: the landing
page advertised 25 rules across three releases that took the number to 32, and
the README's roadmap table still called 0.6 "27 rules" while describing 0.4's
work. Hand-maintained facts about a growing registry do not stay true — so they
stop being hand-maintained.

    python scripts/generate_docs.py            # write docs/generated/*.md
    python scripts/generate_docs.py --check    # exit 1 if any file is stale

`release.py` runs the first; `test_generated_docs.py` runs the second, so a rule
added between releases turns the suite red rather than waiting for someone to cut
one. Prose links to these files instead of repeating them.
"""

import argparse
import json
import sys
from collections import Counter, defaultdict
from collections.abc import Callable
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_OUT = _REPO / "docs" / "generated"

sys.path.insert(0, str(_REPO / "packages" / "guardana-core" / "src"))
sys.path.insert(0, str(_REPO / "packages" / "guardana-rules" / "src"))

from guardana.core import __version__  # noqa: E402
from guardana.core.evaluator.guard import GuardEvaluator  # noqa: E402
from guardana.core.evaluator.llm_judge import LlmJudgeEvaluator  # noqa: E402
from guardana.core.rule.base import Rule  # noqa: E402
from guardana.core.severity import Severity  # noqa: E402
from guardana.core.surface import Surface  # noqa: E402
from guardana.core.target import TargetKind  # noqa: E402
from guardana.rules import provide_evaluators, provide_rules  # noqa: E402

_HEADER = (
    "<!-- Generated by scripts/generate_docs.py from the installed registry. "
    "Do not edit by hand: run `uv run python scripts/generate_docs.py`. -->\n\n"
)

_FRONTMATTER: dict[str, tuple[str, int, str]] = {
    "rule-summary.md": (
        "Rule summary",
        10,
        "Counts by surface, target kind and severity — the totals every other page quotes.",
    ),
    "rule-catalog.md": (
        "Rule catalog",
        20,
        "Every built-in rule, its severity, the surface it runs on, and what it maps to.",
    ),
    "evaluator-catalog.md": (
        "Evaluator catalog",
        30,
        "Every evaluator a rule can name, and what each one grades on.",
    ),
    "taxonomy-coverage.md": (
        "Taxonomy coverage",
        40,
        "Which entry of each public framework at least one built-in rule maps to.",
    ),
}
"""Nav metadata for the generated pages, alongside the code that writes them.

The hand-written pages carry their own frontmatter, and the site build refuses a
page without a title rather than inferring one from the filename. These four have
no author to write it, so it lives here — beside the renderer, in the same file a
new generated page would be added to.
"""


def _front(name: str) -> str:
    title, nav_order, summary = _FRONTMATTER[name]
    return (
        f"---\ntitle: {title}\nnav_order: {nav_order}\n"
        f'summary: "{summary}"\nstatus: stable\n---\n\n'
    )


def _rules() -> list[Rule]:
    return sorted(provide_rules(), key=lambda r: r.meta.id)


def _summary(rules: list[Rule]) -> str:
    by_surface = Counter(r.meta.surface for r in rules)
    by_kind = Counter(r.meta.target_kind for r in rules)
    by_severity = Counter(r.meta.severity for r in rules)
    lines = [
        _HEADER,
        f"**{len(rules)} built-in rules** ship with `guardana-rules` {__version__}.\n",
        "| Facet | Count |",
        "|---|---:|",
        f"| Build-time (`scan`) | {by_surface[Surface.BUILD]} |",
        f"| Runtime (`probe`, `monitor`) | {by_surface[Surface.RUNTIME]} |",
        f"| Against artifacts | {by_kind[TargetKind.ARTIFACT]} |",
        f"| Against endpoints | {by_kind[TargetKind.ENDPOINT]} |",
    ]
    lines += [
        f"| Severity {severity.name} | {by_severity[severity]} |"
        for severity in sorted(Severity, reverse=True)
        if by_severity[severity]
    ]
    return "\n".join(lines) + "\n"


def _catalog(rules: list[Rule]) -> str:
    lines = [
        _HEADER,
        "Every built-in rule, its severity, the surface it runs on, and the",
        "frameworks it maps to. A rule without a mapping does not ship.\n",
        "| Rule | Severity | Surface | Maps to |",
        "|---|---|---|---|",
    ]
    for rule in rules:
        meta = rule.meta
        taxonomy = ", ".join(f"`{t.reference}`" for t in meta.taxonomy) or "—"
        lines.append(f"| `{meta.id}` | {meta.severity.name} | {meta.surface.value} | {taxonomy} |")
    return "\n".join(lines) + "\n"


def _evaluators() -> str:
    always = {e.id: type(e).__doc__ or "" for e in provide_evaluators()}
    configured = {
        LlmJudgeEvaluator.id: LlmJudgeEvaluator.__doc__ or "",
        GuardEvaluator.id: GuardEvaluator.__doc__ or "",
    }
    lines = [
        _HEADER,
        "An evaluator turns a model's reply into a verdict with a confidence.",
        "A rule names one by id, so swapping graders never touches the rule.\n",
        "| Evaluator | Available | What it grades on |",
        "|---|---|---|",
    ]
    lines += [f"| `{name}` | always | {_first_line(doc)} |" for name, doc in sorted(always.items())]
    lines += [
        f"| `{name}` | when configured | {_first_line(doc)} |"
        for name, doc in sorted(configured.items())
    ]
    return "\n".join(lines) + "\n"


def _taxonomy(rules: list[Rule]) -> str:
    per_framework: defaultdict[str, set[str]] = defaultdict(set)
    for rule in rules:
        for ref in rule.meta.taxonomy:
            per_framework[ref.framework].add(ref.id)
    lines = [
        _HEADER,
        "Which entries of each framework at least one built-in rule maps to.",
        "Coverage of an entry is not a claim that the entry is fully addressed —",
        "see `ROADMAP.md` for the honest per-category assessment.\n",
        "| Framework | Entries covered |",
        "|---|---|",
    ]
    for framework in sorted(per_framework):
        entries = ", ".join(f"`{e}`" for e in sorted(per_framework[framework]))
        lines.append(f"| {framework} | {entries} |")
    return "\n".join(lines) + "\n"


def _first_line(doc: str) -> str:
    return doc.strip().splitlines()[0].strip() if doc.strip() else "—"


RULES_JSON_SCHEMA_VERSION = 1
"""Version of `rules.json`, because a generated document is still a document.

Regenerating it is free, so this is not about migration — it is about a consumer
being able to tell which shape it is holding. The rule explorer on the site is one
such consumer; a team rendering their own explorer over their own pack is the
other, and that one is not in this repository.
"""


def _family(rule_id: str) -> str:
    """Take the part of an id that groups rules a reader thinks about together.

    `guardana.supply_chain.pickle_opcode` is supply chain; `acme.agent.customer_data`
    is agent. Taken from the id rather than declared, because the id is what a
    profile's include/exclude globs already select on — a second, declared grouping
    could disagree with the one people actually filter by.
    """
    parts = rule_id.split(".")
    return parts[1] if len(parts) > 1 else parts[0]


def _goal(rule: Rule) -> str | None:
    """Read the sentence a rule's own expectation gives for what a secure answer looks like.

    Taken from `declared_expectations()`, which is the public contract, so a third
    party's pack renders the same way. A rule that grades entirely in Python
    declares no expectation and gets `null` here — not an empty string and not a
    docstring scraped off its class, because several rules share one class and the
    explorer would then attribute one rule's reasoning to another.
    """
    for _evaluator_id, expectation in rule.declared_expectations():
        goal = getattr(expectation, "goal", None)
        if isinstance(goal, str) and goal.strip():
            return goal.strip()
    return None


def _rule_entry(rule: Rule) -> dict[str, object]:
    meta = rule.meta
    return {
        "id": meta.id,
        "namespace": meta.id.split(".")[0],
        "family": _family(meta.id),
        "title": meta.title,
        "severity": meta.severity.name,
        "surface": meta.surface.value,
        "target_kind": str(meta.target_kind),
        "evaluator": meta.evaluator,
        "impact": str(meta.impact),
        "destructive": meta.destructive,
        "maturity": str(meta.maturity),
        "requires": sorted(str(capability) for capability in meta.required_capabilities),
        "estimated_requests": rule.estimated_requests,
        "goal": _goal(rule),
        "taxonomy": [
            {
                "reference": ref.reference,
                "framework": ref.framework,
                "id": ref.id,
                "title": ref.title,
                "rank": ref.rank,
            }
            for ref in meta.taxonomy
        ],
    }


def _rules_json(rules: list[Rule]) -> str:
    """Render the same registry walk as `rule-catalog.md`, for a build rather than a reader.

    The markdown table answers "what ships" in four columns because that is what a
    page of prose can carry. The site's rule explorer needs the other facets too —
    what a rule costs, what it does to the target, which capabilities it needs —
    and inventing a second walk to get them is how the explorer would start
    disagreeing with the catalogue. One walk, two renderings; a test pins them to
    each other.
    """
    return (
        json.dumps(
            {
                "schema_version": RULES_JSON_SCHEMA_VERSION,
                "generated_by": "scripts/generate_docs.py from the installed registry — "
                "do not edit by hand",
                "guardana_version": __version__,
                "rules": [_rule_entry(rule) for rule in rules],
            },
            indent=2,
        )
        + "\n"
    )


def _evaluator_catalog(_rules: list[Rule]) -> str:
    """Render the evaluator catalog. Takes the rule list for a uniform signature."""
    return _evaluators()


_FILES: dict[str, Callable[[list[Rule]], str]] = {
    "rule-summary.md": _summary,
    "rule-catalog.md": _catalog,
    "evaluator-catalog.md": _evaluator_catalog,
    "taxonomy-coverage.md": _taxonomy,
    "rules.json": _rules_json,
}


_PACK_MANIFEST = (
    _REPO / "packages" / "guardana-rules" / "src" / "guardana" / "rules" / "guardana-pack.yaml"
)


def _pack_manifest(rules: list[Rule]) -> str:
    """Render the built-in pack's own manifest from the registry.

    Generated, not hand-written, and that is the whole point: `provides:` is a list
    of every id this pack registers, and a hand-maintained copy of 51 ids is the
    shape of every stale claim this repository has had to fix. A third party writes
    theirs by hand because theirs is short; ours is long, so ours comes from the
    registry and `pack validate` compares the two.
    """
    evaluators = sorted(e.id for e in provide_evaluators())
    return (
        "# Generated by scripts/generate_docs.py — do not edit.\n"
        "#\n"
        "# The manifest for Guardana's own rule pack, which goes through the third\n"
        "# party's door on purpose: a validator this repository exempted itself from\n"
        "# would be a bar we ask other people to clear alone, and the first drift it\n"
        "# would stop catching is our own.\n"
        "#\n"
        "# `provides:` is generated from the registry rather than typed, because a\n"
        "# hand-maintained list of this length is how every stale count here began.\n"
        "# `guardana pack validate` compares it against what the entry points really\n"
        "# register, so a rule renamed in one place and not the other fails the build.\n"
        "#\n"
        "# Documentation: docs/usage-pack.md\n"
        "# Reasoning:     docs/design/extension-author-tooling.md\n"
        "\n"
        "schema_version: 1\n"
        "name: guardana-rules\n"
        "\n"
        "# Versioned separately from the product: in 0.x the product's minor breaks API\n"
        "# by design, and a pack pinned to a product range would need re-releasing on\n"
        "# every minor even when nothing it touches moved.\n"
        'extension_api: ">=1,<2"\n'
        "\n"
        "description: >\n"
        "  The built-in rules: model and dependency supply chain, prompt and jailbreak\n"
        "  probes, agent and MCP checks, and the trace rules that grade a recorded\n"
        "  execution. Every rule maps to a public framework.\n"
        "\n"
        "provides:\n"
        "  rules:\n"
        + "".join(f"    - {rule.meta.id}\n" for rule in sorted(rules, key=lambda r: r.meta.id))
        + "  evaluators:\n"
        + "".join(f"    - {name}\n" for name in evaluators)
    )


def main() -> int:
    """Write the generated fragments, or report which are stale."""
    parser = argparse.ArgumentParser(description="Generate documentation from the registry.")
    parser.add_argument("--check", action="store_true", help="exit 1 if stale; write nothing")
    args = parser.parse_args()

    _OUT.mkdir(parents=True, exist_ok=True)
    rules = _rules()
    stale: list[str] = []
    for name, render in _FILES.items():
        path = _OUT / name
        wanted = render(rules)
        if name in _FRONTMATTER:
            wanted = _front(name) + wanted
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == wanted:
            continue
        stale.append(name)
        if not args.check:
            path.write_text(wanted, encoding="utf-8")

    manifest = _pack_manifest(rules)
    if _PACK_MANIFEST.read_text(encoding="utf-8") != manifest:
        stale.append("guardana-pack.yaml")
        if not args.check:
            _PACK_MANIFEST.write_text(manifest, encoding="utf-8")

    if not stale:
        print("docs/generated is current")
        return 0
    if args.check:
        print("docs/generated is out of date: " + ", ".join(stale))
        print("run `uv run python scripts/generate_docs.py` to refresh it")
        return 1
    print("regenerated: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
