"""Generate the factual documentation fragments from the installed registry.

Every count this project states in prose has drifted at least once: the landing
page advertised 25 rules across three releases that took the number to 32, and
the README's roadmap table still called 0.6 "27 rules" while describing 0.4's
work. Hand-maintained facts about a growing registry do not stay true — so they
stop being hand-maintained.

    python scripts/generate_docs.py            # write docs/generated/*.md
    python scripts/generate_docs.py --check    # exit 1 if any file is stale

`release.py` runs the first; `test_generated_docs.py` runs the second, so a rule
added between releases turns the suite red rather than waiting for someone to cut
one. Prose links to these files instead of repeating them.
"""

import argparse
import json
import sys
import tomllib
from collections import Counter, defaultdict
from collections.abc import Callable
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_OUT = _REPO / "docs" / "generated"
_BUILT_IN_MANIFEST_SCHEMA = 2  # declares no output, so older builds keep reading it

sys.path.insert(0, str(_REPO / "packages" / "guardana-core" / "src"))
sys.path.insert(0, str(_REPO / "packages" / "guardana-rules" / "src"))

from guardana.core import __version__  # noqa: E402
from guardana.core.evaluator import CONFIG_WIRED  # noqa: E402
from guardana.core.evaluator.base import Evaluator  # noqa: E402
from guardana.core.manifest.model import MANIFEST_SCHEMA_VERSION  # noqa: E402
from guardana.core.output import OUTPUT_API_VERSION  # noqa: E402
from guardana.core.pack.lock import LOCK_SCHEMA_VERSION  # noqa: E402
from guardana.core.pack.model import EXTENSION_API_VERSION, PACK_SCHEMA_VERSION  # noqa: E402
from guardana.core.profile.loader import PROFILE_SCHEMA_VERSION  # noqa: E402
from guardana.core.reporter import ENVELOPE_SCHEMA_VERSION  # noqa: E402
from guardana.core.rule.base import Rule, RuleContext  # noqa: E402
from guardana.core.rule.fixture import FixtureOutcome  # noqa: E402
from guardana.core.rule.verify import FixtureVerdict, verify_rule  # noqa: E402
from guardana.core.safety import Detection  # noqa: E402
from guardana.core.severity import Severity  # noqa: E402
from guardana.core.surface import Surface  # noqa: E402
from guardana.core.target import TargetKind  # noqa: E402
from guardana.rules import provide_evaluators, provide_rules  # noqa: E402

import adopter_measure  # noqa: E402
import api_surface  # noqa: E402
import first_run_measure  # noqa: E402

_HEADER = (
    "<!-- Generated by scripts/generate_docs.py from the installed registry. "
    "Do not edit by hand: run `uv run python scripts/generate_docs.py`. -->\n\n"
)

_FRONTMATTER: dict[str, tuple[str, int, str]] = {
    "rule-summary.md": (
        "Rule summary",
        10,
        "Counts by surface, target kind and severity — the totals every other page quotes.",
    ),
    "rule-catalog.md": (
        "Rule catalog",
        20,
        "Every built-in rule, its severity, surface, target, maturity, and what it maps to.",
    ),
    "evaluator-catalog.md": (
        "Evaluator catalog",
        30,
        "Every evaluator a rule can name, and what each one grades on.",
    ),
    "taxonomy-coverage.md": (
        "Taxonomy coverage",
        40,
        "Which entry of each public framework at least one built-in rule maps to.",
    ),
    "detection-limits.md": (
        "Detection limits",
        50,
        "Per rule family, whether a finding is a tested invariant, a heuristic lead, "
        "or undeclared.",
    ),
    "first-run.md": (
        "First-run measure",
        60,
        "Whether new users reach a failing result, a fix, saved evidence and an edited "
        "check within ten minutes, from the recorded study sheet.",
    ),
    "compatibility-matrix.md": (
        "Compatibility matrix",
        70,
        "Which document, envelope and API versions each minor release writes, from the "
        "documents those releases wrote.",
    ),
    "application-measures.md": (
        "Application measures",
        80,
        "Coverage of the real application and the supported-verdict share, from locked "
        "application runs teams recorded with their consent.",
    ),
}
"""Nav metadata for the generated pages, alongside the code that writes them.

The hand-written pages carry their own frontmatter, and the site build refuses a
page without a title rather than inferring one from the filename. These pages have
no author to write it, so it lives here — beside the renderer, in the same file a
new generated page would be added to.
"""


def _front(name: str) -> str:
    title, nav_order, summary = _FRONTMATTER[name]
    return (
        f"---\ntitle: {title}\nnav_order: {nav_order}\n"
        f'summary: "{summary}"\nstatus: stable\n---\n\n'
    )


def _rules() -> list[Rule]:
    return sorted(provide_rules(), key=lambda r: r.meta.id)


def _summary(rules: list[Rule]) -> str:
    by_surface = Counter(r.meta.surface for r in rules)
    by_kind = Counter(r.meta.target_kind for r in rules)
    by_severity = Counter(r.meta.severity for r in rules)
    lines = [
        _HEADER,
        f"**{len(rules)} built-in rules** ship with `guardana-rules` {__version__}.\n",
        "| Facet | Count |",
        "|---|---:|",
        f"| Build-time (`scan`) | {by_surface[Surface.BUILD]} |",
        f"| Runtime (`probe`, `monitor`) | {by_surface[Surface.RUNTIME]} |",
        f"| Against artifacts | {by_kind[TargetKind.ARTIFACT]} |",
        f"| Against endpoints | {by_kind[TargetKind.ENDPOINT]} |",
    ]
    lines += [
        f"| Severity {severity.name} | {by_severity[severity]} |"
        for severity in sorted(Severity, reverse=True)
        if by_severity[severity]
    ]
    ctx = RuleContext(evaluators={type(e).id: e for e in provide_evaluators()})
    proven = sum(verify_rule(rule, ctx).is_proven for rule in rules)
    lines.append(f"| Proven by their own finding, clean and inconclusive samples | {proven} |")
    return "\n".join(lines) + "\n"


def _catalog(rules: list[Rule]) -> str:
    lines = [
        _HEADER,
        "Every built-in rule, its severity, the surface it runs on, the kind of",
        "target it reads, its maturity, and the frameworks it maps to. A rule",
        "without a mapping does not ship.\n",
        "| Rule | Severity | Surface | Target | Maturity | Maps to |",
        "|---|---|---|---|---|---|",
    ]
    for rule in rules:
        meta = rule.meta
        taxonomy = ", ".join(f"`{t.reference}`" for t in meta.taxonomy) or "—"
        lines.append(
            f"| `{meta.id}` | {meta.severity.name} | {meta.surface.value} "
            f"| {meta.target_kind} | {meta.maturity} | {taxonomy} |"
        )
    return "\n".join(lines) + "\n"


def _evaluators() -> str:
    always = {type(e).id: type(e) for e in provide_evaluators()}
    configured: dict[str, type[Evaluator]] = {kind.id: kind for kind in CONFIG_WIRED}
    lines = [
        _HEADER,
        "An evaluator turns a model's reply into a verdict with a confidence.",
        "A rule names one by id, so swapping graders never touches the rule.\n",
        "| Evaluator | Available | What it grades on | Error correction |",
        "|---|---|---|---|",
    ]
    lines += [_evaluator_row(name, "always", kind) for name, kind in sorted(always.items())]
    lines += [
        _evaluator_row(name, "when configured", kind) for name, kind in sorted(configured.items())
    ]
    return "\n".join(lines) + "\n"


def _evaluator_row(name: str, available: str, kind: type[Evaluator]) -> str:
    correction = "Not needed" if kind.deterministic is True else "With matching calibration"
    return f"| `{name}` | {available} | {_first_line(kind.__doc__ or '')} | {correction} |"


def _taxonomy(rules: list[Rule]) -> str:
    per_framework: defaultdict[str, set[str]] = defaultdict(set)
    for rule in rules:
        for ref in rule.meta.taxonomy:
            per_framework[ref.framework].add(ref.id)
    lines = [
        _HEADER,
        "Which entries of each framework at least one built-in rule maps to.",
        "Coverage of an entry is not a claim that the entry is fully addressed —",
        "See [detection limits](detection-limits.md) for what each rule proves.\n",
        "| Framework | Entries covered |",
        "|---|---|",
    ]
    for framework in sorted(per_framework):
        entries = ", ".join(f"`{e}`" for e in sorted(per_framework[framework]))
        lines.append(f"| {framework} | {entries} |")
    return "\n".join(lines) + "\n"


def _first_line(doc: str) -> str:
    return doc.strip().splitlines()[0].strip() if doc.strip() else "—"


RULES_JSON_SCHEMA_VERSION = 1
"""Version of `rules.json`, because a generated document is still a document.

Regenerating it is free, so this is not about migration — it is about a consumer
being able to tell which shape it is holding. The rule explorer on the site is one
such consumer; a team rendering their own explorer over their own pack is the
other, and that one is not in this repository.
"""


def _family(rule_id: str) -> str:
    """Take the part of an id that groups rules a reader thinks about together.

    `guardana.supply_chain.pickle_opcode` is supply chain; `acme.agent.customer_data`
    is agent. Taken from the id rather than declared, because the id is what a
    profile's include/exclude globs already select on — a second, declared grouping
    could disagree with the one people actually filter by.
    """
    parts = rule_id.split(".")
    return parts[1] if len(parts) > 1 else parts[0]


def _goal(rule: Rule) -> str | None:
    """Read the sentence a rule's own expectation gives for what a secure answer looks like.

    Taken from `declared_expectations()`, which is the public contract, so a third
    party's pack renders the same way. A rule that grades entirely in Python
    declares no expectation and gets `null` here — not an empty string and not a
    docstring scraped off its class, because several rules share one class and the
    explorer would then attribute one rule's reasoning to another.
    """
    for _evaluator_id, expectation in rule.declared_expectations():
        goal = getattr(expectation, "goal", None)
        if isinstance(goal, str) and goal.strip():
            return goal.strip()
    return None


def _rule_entry(rule: Rule) -> dict[str, object]:
    meta = rule.meta
    return {
        "id": meta.id,
        "namespace": meta.id.split(".")[0],
        "family": _family(meta.id),
        "title": meta.title,
        "severity": meta.severity.name,
        "surface": meta.surface.value,
        "target_kind": str(meta.target_kind),
        "evaluator": meta.evaluator,
        "impact": str(meta.impact),
        "destructive": meta.destructive,
        "maturity": str(meta.maturity),
        "detection": str(meta.detection),
        "requires": sorted(str(capability) for capability in meta.required_capabilities),
        "estimated_requests": rule.estimated_requests,
        "goal": _goal(rule),
        "taxonomy": [
            {
                "reference": ref.reference,
                "framework": ref.framework,
                "id": ref.id,
                "title": ref.title,
                "rank": ref.rank,
            }
            for ref in meta.taxonomy
        ],
    }


def _rules_json(rules: list[Rule]) -> str:
    """Render the same registry walk as `rule-catalog.md`, for a build rather than a reader.

    The markdown table answers "what ships" in six columns because that is what a
    page of prose can carry. The site's rule explorer needs the other facets too —
    what a rule costs, what it does to the target, which capabilities it needs —
    and inventing a second walk to get them is how the explorer would start
    disagreeing with the catalogue. One walk, two renderings; a test pins them to
    each other.
    """
    return (
        json.dumps(
            {
                "schema_version": RULES_JSON_SCHEMA_VERSION,
                "generated_by": "scripts/generate_docs.py from the installed registry — "
                "do not edit by hand",
                "guardana_version": __version__,
                "rules": [_rule_entry(rule) for rule in rules],
            },
            indent=2,
        )
        + "\n"
    )


def _evaluator_catalog(_rules: list[Rule]) -> str:
    """Render the evaluator catalog. Takes the rule list for a uniform signature."""
    return _evaluators()


_DETECTION_PREAMBLE = (
    "What a finding from each built-in rule states about the target, grouped by rule "
    "family and read from the `detection` each rule declares.\n\n"
    "- **Tested invariant**: every finding the rule can emit states a checked fact about "
    "the target (a planted marker seen in output, a byte sequence or opcode present, a "
    "server answering without credentials, a recorded span showing the forbidden step), "
    "and the rule ships a finding sample and a clean sample that it classifies correctly.\n"
    "- **Invariant, not sampled**: the rule declares that every finding states a checked "
    "fact, and does not ship both a finding sample and a clean sample that it classifies "
    "correctly.\n"
    "- **Heuristic lead**: a finding is a lead a person confirms. A keyword, a phrase or "
    "name list, a threshold, an entropy or pattern match decides whether the risk is real. "
    "A rule that can emit both kinds is listed here.\n"
    "- **Not declared**: the rule does not say which of the two its findings are.\n\n"
    "A framework mapping says a rule is relevant to that entry, not that the entry is "
    "covered.\n"
)

_TESTED = "Tested invariant"
_UNSAMPLED = "Invariant, not sampled"
_LEAD = "Heuristic lead"
_UNDECLARED = "Not declared"
_GROUPS = (_TESTED, _UNSAMPLED, _LEAD, _UNDECLARED)


def _detection_group(rule: Rule, sampled: Callable[[Rule], bool]) -> str:
    """Name the group a rule is printed under; anything but the two labels is not declared."""
    detection = rule.meta.detection
    if detection is Detection.INVARIANT:
        return _TESTED if sampled(rule) else _UNSAMPLED
    if detection is Detection.HEURISTIC:
        return _LEAD
    return _UNDECLARED


def _ships_both_samples(rule: Rule, ctx: RuleContext) -> bool:
    """Whether the rule classifies a finding sample and a clean sample of its own correctly.

    A sample that failed or could not run shows nothing, so one such result is enough
    to leave the rule unsampled rather than tested.
    """
    verification = verify_rule(rule, ctx)
    if verification.failed or verification.errored:
        return False
    passed = {
        result.expected
        for result in verification.results
        if result.verdict is FixtureVerdict.PASSED
    }
    return {FixtureOutcome.FINDING, FixtureOutcome.CLEAN} <= passed


def _detection_page(rules: list[Rule], sampled: Callable[[Rule], bool]) -> str:
    """Render the detection-limits page for `rules`, deciding "tested" with `sampled`."""
    families: defaultdict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        families[_family(rule.meta.id)].append(rule)
    lines = [_HEADER + _DETECTION_PREAMBLE]
    for family in sorted(families):
        members = sorted(families[family], key=lambda r: r.meta.id)
        lines.append(f"## {family}\n")
        grouped: defaultdict[str, list[Rule]] = defaultdict(list)
        for rule in members:
            grouped[_detection_group(rule, sampled)].append(rule)
        for group in _GROUPS:
            if grouped[group]:
                lines.append(f"### {group}\n")
                lines += [f"- `{r.meta.id}`: {r.meta.title}" for r in grouped[group]]
                lines.append("")
        references = {ref.reference: ref for rule in members for ref in rule.meta.taxonomy}
        lines.append("### Framework entries these rules are relevant to, not coverage of them\n")
        if references:
            lines += [
                f"- `{reference}`: {references[reference].title}"
                for reference in sorted(references)
            ]
        else:
            lines.append("- none mapped")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _detection_limits(rules: list[Rule]) -> str:
    """Render the detection-limits page, running each rule's own samples to tell tested apart."""
    ctx = RuleContext(evaluators={type(e).id: e for e in provide_evaluators()})
    return _detection_page(rules, lambda rule: _ships_both_samples(rule, ctx))


def _first_run(_rules: list[Rule]) -> str:
    """Render the first-run measure from `docs/studies/first-run-study.csv` only."""
    return (
        _HEADER.replace("the installed registry", "docs/studies/first-run-study.csv")
        + "# First-run measure\n\n"
        + "Sessions run as described in "
        + "[the first-run study](../studies/first-run-study.md): a participant new to "
        + "Guardana, a clean environment, the published release and the README only.\n\n"
        + first_run_measure.render(first_run_measure.read_sheet())
    )


def _application_measures(_rules: list[Rule]) -> str:
    """Render the two adopter measures from `docs/studies/adopter-runs.csv` only."""
    return (
        _HEADER.replace("the installed registry", "docs/studies/adopter-runs.csv")
        + "# Application measures\n\n"
        + "Counts from locked application runs that teams recorded, with their consent to "
        + "publish, in `docs/studies/adopter-runs.csv`. The coverage of the real "
        + "application is the rules attempted out of the rules that apply to it; the "
        + "supported-verdict share is the rules that reached a finding or a clean result out "
        + "of the rules attempted.\n\n"
        + adopter_measure.render()
    )


_HISTORY = _REPO / "packages" / "guardana-core" / "tests" / "historical" / "releases.json"
_CORE_PYPROJECT = _REPO / "packages" / "guardana-core" / "pyproject.toml"
_MATRIX_COLUMNS = (
    "Release",
    "Python",
    "Run schema",
    "Envelope",
    "Pack manifest",
    "Lock",
    "Profile",
    "Extension API",
    "Output API",
)
_MATRIX_KINDS = ("run", "envelope", "pack-manifest", "pack-lock", "profile")
_RELEASE_PARTS = 3
_ABSENT = "—"
_MATRIX_LEGEND = (
    f"{_ABSENT} means the release wrote no such document when it was captured, wrote it "
    "without a version key, or defines no such API version."
)


def _python_versions(classifiers: list[str]) -> str:
    return ", ".join(classifiers) if classifiers else _ABSENT


def _current_row() -> list[str]:
    """Build this tree's row from its own constants and its `Programming Language` classifiers."""
    project = tomllib.loads(_CORE_PYPROJECT.read_text(encoding="utf-8"))["project"]
    prefix = "Programming Language :: Python :: "
    pythons = [
        c.removeprefix(prefix)
        for c in project.get("classifiers", [])
        if c.startswith(prefix) and c.removeprefix(prefix).count(".") == 1
    ]
    return [
        "this tree",
        _python_versions(pythons),
        *(
            str(version)
            for version in (
                MANIFEST_SCHEMA_VERSION,
                ENVELOPE_SCHEMA_VERSION,
                PACK_SCHEMA_VERSION,
                LOCK_SCHEMA_VERSION,
                PROFILE_SCHEMA_VERSION,
                EXTENSION_API_VERSION,
                OUTPUT_API_VERSION,
            )
        ),
    ]


def _written(kind: dict[str, object]) -> str:
    version = kind.get("schema_version")
    if kind["produced"] is not True or version is None:
        return _ABSENT
    if isinstance(version, int) and not isinstance(version, bool):
        return str(version)
    raise ValueError(f"schema_version {version!r} is not an integer")


def _api(version: object) -> str:
    if version is None:
        return _ABSENT
    if isinstance(version, int) and not isinstance(version, bool):
        return str(version)
    raise ValueError(f"API version {version!r} is not an integer")


def _release_row(release: str, entry: dict[str, object]) -> list[str]:
    """One release's row, as its record states it."""
    kinds = entry["kinds"]
    classifiers = entry["python_classifiers"]
    if not isinstance(kinds, dict) or not isinstance(classifiers, list):
        raise TypeError("kinds or python_classifiers has the wrong shape")
    return [
        release,
        _python_versions(classifiers),
        *(_written(kinds[kind]) for kind in _MATRIX_KINDS),
        _api(entry["extension_api_version"]),
        _api(entry["output_api_version"]),
    ]


def _release_rows(history: dict[str, dict[str, object]]) -> list[list[str]]:
    """One row per minor release, from its newest patch, newest minor first."""
    newest: dict[tuple[int, ...], tuple[tuple[int, ...], str]] = {}
    for release in history:
        parts = tuple(int(part) for part in release.split("."))
        if len(parts) != _RELEASE_PARTS:
            raise ValueError(f"{release} is not a MAJOR.MINOR.PATCH release")
        if parts[:2] not in newest or parts > newest[parts[:2]][0]:
            newest[parts[:2]] = (parts, release)
    rows = []
    for minor in sorted(newest, reverse=True):
        release = newest[minor][1]
        try:
            rows.append(_release_row(release, history[release]))
        except (KeyError, TypeError, ValueError) as error:
            raise ValueError(f"{_HISTORY.name}: {release}: {error}") from error
    return rows


def _matrix_table(rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(_MATRIX_COLUMNS) + " |",
        "|" + "---|" * len(_MATRIX_COLUMNS),
        *("| " + " | ".join(row) + " |" for row in rows),
    ]
    return "\n".join(lines) + "\n"


def _compatibility_matrix(_rules: list[Rule], history_path: Path | None = None) -> str:
    """Render the matrix from the recorded releases, or say it is not generated without them.

    The releases come from `historical/releases.json`, which the capture of older documents
    writes; a cell the record does not hold is shown as absent, never filled in.
    """
    path = _HISTORY if history_path is None else history_path
    page = (
        _HEADER.replace("the installed registry", "the recorded releases and this tree")
        + "# Compatibility matrix\n\n"
        + "What each release writes and which API versions it defines. The policy these "
        + "versions follow is on the [compatibility page](../compatibility.md).\n\n"
    )
    if not path.is_file():
        return (
            page
            + "**Not generated yet.** The documents older releases wrote are not recorded in "
            + "this tree, so no release has a row. The one row below is this tree, read from "
            + "its own constants.\n\n"
            + _matrix_table([_current_row()])
        )
    history = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(history, dict):
        raise TypeError(f"{path.name} is not an object keyed by release")
    return (
        page
        + "One row per minor release, from its newest patch, as that release wrote its "
        + "documents when it was captured; a pack manifest and a lock were captured for a "
        + "pack without outputs. The first row is this tree, read from its own constants, "
        + "and shows the newest version it writes.\n\n"
        + _matrix_table([_current_row(), *_release_rows(history)])
        + "\n"
        + _MATRIX_LEGEND
        + "\n"
    )


def _api_surface(_rules: list[Rule]) -> str:
    """Render the supported surface snapshot, read from source by `scripts/api_surface.py`."""
    return api_surface.render()


_FILES: dict[str, Callable[[list[Rule]], str]] = {
    "rule-summary.md": _summary,
    "rule-catalog.md": _catalog,
    "evaluator-catalog.md": _evaluator_catalog,
    "taxonomy-coverage.md": _taxonomy,
    "detection-limits.md": _detection_limits,
    "first-run.md": _first_run,
    "compatibility-matrix.md": _compatibility_matrix,
    "application-measures.md": _application_measures,
    "rules.json": _rules_json,
    "api-surface.json": _api_surface,
}


_PACK_MANIFEST = (
    _REPO / "packages" / "guardana-rules" / "src" / "guardana" / "rules" / "guardana-pack.yaml"
)


def _pack_manifest(rules: list[Rule]) -> str:
    """Render the built-in pack's own manifest from the registry.

    Generated, not hand-written, and that is the whole point: `provides:` is a list
    of every id this pack registers, and a hand-maintained copy of 51 ids is the
    shape of every stale claim this repository has had to fix. A third party writes
    theirs by hand because theirs is short; ours is long, so ours comes from the
    registry and `pack validate` compares the two.
    """
    evaluators = sorted(e.id for e in provide_evaluators())
    return (
        "# Generated by scripts/generate_docs.py — do not edit.\n"
        "#\n"
        "# The manifest for Guardana's own rule pack, which goes through the third\n"
        "# party's door on purpose: a validator this repository exempted itself from\n"
        "# would be a bar we ask other people to clear alone, and the first drift it\n"
        "# would stop catching is our own.\n"
        "#\n"
        "# `provides:` is generated from the registry rather than typed, because a\n"
        "# hand-maintained list of this length is how every stale count here began.\n"
        "# `guardana pack validate` compares it against what the entry points really\n"
        "# register, so a rule renamed in one place and not the other fails the build.\n"
        "#\n"
        "# Documentation: docs/usage-pack.md\n"
        "\n"
        f"schema_version: {_BUILT_IN_MANIFEST_SCHEMA}\n"
        "name: guardana-rules\n"
        "\n"
        "# Versioned separately from the product: in 0.x the product's minor breaks API\n"
        "# by design, and a pack pinned to a product range would need re-releasing on\n"
        "# every minor even when nothing it touches moved.\n"
        'extension_api: ">=1,<2"\n'
        "\n"
        "description: >\n"
        "  The built-in rules: model and dependency supply chain, prompt and jailbreak\n"
        "  probes, agent and MCP checks, and the trace rules that grade a recorded\n"
        "  execution. Every rule maps to a public framework.\n"
        "\n"
        "provides:\n"
        "  rules:\n"
        + "".join(f"    - {rule.meta.id}\n" for rule in sorted(rules, key=lambda r: r.meta.id))
        + "  evaluators:\n"
        + "".join(f"    - {name}\n" for name in evaluators)
    )


def main() -> int:
    """Write the generated fragments, or report which are stale."""
    parser = argparse.ArgumentParser(description="Generate documentation from the registry.")
    parser.add_argument("--check", action="store_true", help="exit 1 if stale; write nothing")
    args = parser.parse_args()

    _OUT.mkdir(parents=True, exist_ok=True)
    rules = _rules()
    stale: list[str] = []
    for name, render in _FILES.items():
        path = _OUT / name
        wanted = render(rules)
        if name in _FRONTMATTER:
            wanted = _front(name) + wanted
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == wanted:
            continue
        stale.append(name)
        if not args.check:
            path.write_text(wanted, encoding="utf-8")

    manifest = _pack_manifest(rules)
    if _PACK_MANIFEST.read_text(encoding="utf-8") != manifest:
        stale.append("guardana-pack.yaml")
        if not args.check:
            _PACK_MANIFEST.write_text(manifest, encoding="utf-8")

    if not stale:
        print("docs/generated is current")
        return 0
    if args.check:
        print("docs/generated is out of date: " + ", ".join(stale))
        print("run `uv run python scripts/generate_docs.py` to refresh it")
        return 1
    print("regenerated: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
