#!/usr/bin/env python3
"""Write a CycloneDX SBOM for each of the five distributions, and check what it wrote.

A release that says "we ship pyyaml and defusedxml" in prose is a claim; an SBOM
is the same claim in a form somebody else's scanner can read. One per
distribution, because that is the unit a user installs: `guardana-cli`'s bill of
materials is not `guardana-server`'s, and a single merged document would tell a
collector operator they had installed Typer.

Generated by `uv export`, which resolves from the same `uv.lock` the tests and the
release run against — no second resolver to disagree with the first, and no new
tooling in the supply chain of a supply-chain scanner.

    uv run python scripts/generate_sbom.py            # writes sbom/
    uv run python scripts/generate_sbom.py --check    # writes, verifies, cleans up

The written file is read back and checked against the package's own metadata,
because the artifact is what ships — an SBOM that was correct in memory and
truncated on disk is worse than none.
"""

import json
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_PACKAGES = (
    "guardana-core",
    "guardana-rules",
    "guardana-report",
    "guardana-cli",
    "guardana-server",
)
_FORMAT = "cyclonedx1.5"


def _version() -> str:
    pyproject = tomllib.loads(
        (_ROOT / "packages" / "guardana-core" / "pyproject.toml").read_text(encoding="utf-8")
    )
    version = pyproject["project"]["version"]
    if not isinstance(version, str):
        raise SystemExit("guardana-core has no version")
    return version


def _declared_dependencies(package: str) -> set[str]:
    """Return the distributions this package's own metadata says it needs."""
    pyproject = tomllib.loads(
        (_ROOT / "packages" / package / "pyproject.toml").read_text(encoding="utf-8")
    )
    names = set()
    for requirement in pyproject["project"].get("dependencies", ()):
        name = requirement.split(";")[0]
        for separator in "<>=!~[( ":
            name = name.split(separator)[0]
        names.add(name.strip().lower().replace("_", "-"))
    return names


def _export(package: str, destination: Path) -> None:
    # S603/S607: every argument is a literal or a repository path, and `uv` is
    # resolved from PATH exactly as every other script here resolves it.
    result = subprocess.run(  # noqa: S603
        [  # noqa: S607 — `uv` from PATH, exactly as bump_version.py and release.py do
            "uv",
            "export",
            "--quiet",
            "--format",
            _FORMAT,
            "--no-dev",
            "--package",
            package,
            "--output-file",
            str(destination),
        ],
        cwd=_ROOT,
        check=False,
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        print(result.stdout + result.stderr, file=sys.stderr)
        raise SystemExit(f"uv export failed for {package}")


def _verify(package: str, version: str, path: Path) -> list[str]:
    """Read the file back and say what is wrong with it, if anything."""
    problems: list[str] = []
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        return [f"could not read the SBOM back: {exc}"]

    if document.get("bomFormat") != "CycloneDX":
        problems.append(f"bomFormat is {document.get('bomFormat')!r}")
    root = document.get("metadata", {}).get("component", {})
    if root.get("name") != package:
        problems.append(f"root component is {root.get('name')!r}, expected {package!r}")
    if root.get("version") != version:
        problems.append(f"root version is {root.get('version')!r}, expected {version!r}")

    listed = {component.get("name") for component in document.get("components", ())}
    missing = sorted(_declared_dependencies(package) - listed)
    if missing:
        # The check that makes this more than a file-exists test: a document that
        # parses but describes the wrong package would pass everything above.
        problems.append(f"does not list this package's own dependencies: {missing}")
    return problems


def main() -> int:
    """Write one SBOM per distribution into `sbom/`, verifying each written file."""
    check_only = "--check" in sys.argv[1:]
    version = _version()
    output = Path(tempfile.mkdtemp(prefix="guardana-sbom-")) if check_only else _ROOT / "sbom"
    output.mkdir(parents=True, exist_ok=True)

    failures = 0
    try:
        for package in _PACKAGES:
            path = output / f"{package}-{version}.cdx.json"
            _export(package, path)
            problems = _verify(package, version, path)
            if problems:
                failures += 1
                print(f"  FAIL  {path.name}: {'; '.join(problems)}")
                continue
            print(f"  ok    {path.name}")
    finally:
        if check_only:
            shutil.rmtree(output, ignore_errors=True)

    if failures:
        print(f"\n{failures} SBOM(s) are not what they claim to be")
        return 1
    print(f"\n{len(_PACKAGES)} SBOMs for {version}" + ("" if check_only else f" in {output}"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
