"""Generate the factual documentation fragments from the installed registry.

Every count this project states in prose has drifted at least once: the landing
page advertised 25 rules across three releases that took the number to 32, and
the README's roadmap table still called 0.6 "27 rules" while describing 0.4's
work. Hand-maintained facts about a growing registry do not stay true — so they
stop being hand-maintained.

    python scripts/generate_docs.py            # write docs/generated/*.md
    python scripts/generate_docs.py --check    # exit 1 if any file is stale

`release.py` runs the first; `test_generated_docs.py` runs the second, so a rule
added between releases turns the suite red rather than waiting for someone to cut
one. Prose links to these files instead of repeating them.
"""

import argparse
import sys
from collections import Counter, defaultdict
from collections.abc import Callable
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_OUT = _REPO / "docs" / "generated"

sys.path.insert(0, str(_REPO / "packages" / "guardana-core" / "src"))
sys.path.insert(0, str(_REPO / "packages" / "guardana-rules" / "src"))

from guardana.core import __version__  # noqa: E402
from guardana.core.evaluator.guard import GuardEvaluator  # noqa: E402
from guardana.core.evaluator.llm_judge import LlmJudgeEvaluator  # noqa: E402
from guardana.core.rule.base import Rule  # noqa: E402
from guardana.core.severity import Severity  # noqa: E402
from guardana.core.surface import Surface  # noqa: E402
from guardana.core.target import TargetKind  # noqa: E402
from guardana.rules import provide_evaluators, provide_rules  # noqa: E402

_HEADER = (
    "<!-- Generated by scripts/generate_docs.py from the installed registry. "
    "Do not edit by hand: run `uv run python scripts/generate_docs.py`. -->\n\n"
)


def _rules() -> list[Rule]:
    return sorted(provide_rules(), key=lambda r: r.meta.id)


def _summary(rules: list[Rule]) -> str:
    by_surface = Counter(r.meta.surface for r in rules)
    by_kind = Counter(r.meta.target_kind for r in rules)
    by_severity = Counter(r.meta.severity for r in rules)
    lines = [
        _HEADER,
        f"**{len(rules)} built-in rules** ship with `guardana-rules` {__version__}.\n",
        "| Facet | Count |",
        "|---|---:|",
        f"| Build-time (`scan`) | {by_surface[Surface.BUILD]} |",
        f"| Runtime (`probe`, `monitor`) | {by_surface[Surface.RUNTIME]} |",
        f"| Against artifacts | {by_kind[TargetKind.ARTIFACT]} |",
        f"| Against endpoints | {by_kind[TargetKind.ENDPOINT]} |",
    ]
    lines += [
        f"| Severity {severity.name} | {by_severity[severity]} |"
        for severity in sorted(Severity, reverse=True)
        if by_severity[severity]
    ]
    return "\n".join(lines) + "\n"


def _catalog(rules: list[Rule]) -> str:
    lines = [
        _HEADER,
        "Every built-in rule, its severity, the surface it runs on, and the",
        "frameworks it maps to. A rule without a mapping does not ship.\n",
        "| Rule | Severity | Surface | Maps to |",
        "|---|---|---|---|",
    ]
    for rule in rules:
        meta = rule.meta
        taxonomy = ", ".join(f"`{t.reference}`" for t in meta.taxonomy) or "—"
        lines.append(f"| `{meta.id}` | {meta.severity.name} | {meta.surface.value} | {taxonomy} |")
    return "\n".join(lines) + "\n"


def _evaluators() -> str:
    always = {e.id: type(e).__doc__ or "" for e in provide_evaluators()}
    configured = {
        LlmJudgeEvaluator.id: LlmJudgeEvaluator.__doc__ or "",
        GuardEvaluator.id: GuardEvaluator.__doc__ or "",
    }
    lines = [
        _HEADER,
        "An evaluator turns a model's reply into a verdict with a confidence.",
        "A rule names one by id, so swapping graders never touches the rule.\n",
        "| Evaluator | Available | What it grades on |",
        "|---|---|---|",
    ]
    lines += [f"| `{name}` | always | {_first_line(doc)} |" for name, doc in sorted(always.items())]
    lines += [
        f"| `{name}` | when configured | {_first_line(doc)} |"
        for name, doc in sorted(configured.items())
    ]
    return "\n".join(lines) + "\n"


def _taxonomy(rules: list[Rule]) -> str:
    per_framework: defaultdict[str, set[str]] = defaultdict(set)
    for rule in rules:
        for ref in rule.meta.taxonomy:
            per_framework[ref.framework].add(ref.id)
    lines = [
        _HEADER,
        "Which entries of each framework at least one built-in rule maps to.",
        "Coverage of an entry is not a claim that the entry is fully addressed —",
        "see `ROADMAP.md` for the honest per-category assessment.\n",
        "| Framework | Entries covered |",
        "|---|---|",
    ]
    for framework in sorted(per_framework):
        entries = ", ".join(f"`{e}`" for e in sorted(per_framework[framework]))
        lines.append(f"| {framework} | {entries} |")
    return "\n".join(lines) + "\n"


def _first_line(doc: str) -> str:
    return doc.strip().splitlines()[0].strip() if doc.strip() else "—"


def _evaluator_catalog(_rules: list[Rule]) -> str:
    """Render the evaluator catalog. Takes the rule list for a uniform signature."""
    return _evaluators()


_FILES: dict[str, Callable[[list[Rule]], str]] = {
    "rule-summary.md": _summary,
    "rule-catalog.md": _catalog,
    "evaluator-catalog.md": _evaluator_catalog,
    "taxonomy-coverage.md": _taxonomy,
}


def main() -> int:
    """Write the generated fragments, or report which are stale."""
    parser = argparse.ArgumentParser(description="Generate documentation from the registry.")
    parser.add_argument("--check", action="store_true", help="exit 1 if stale; write nothing")
    args = parser.parse_args()

    _OUT.mkdir(parents=True, exist_ok=True)
    rules = _rules()
    stale: list[str] = []
    for name, render in _FILES.items():
        path = _OUT / name
        wanted = render(rules)
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == wanted:
            continue
        stale.append(name)
        if not args.check:
            path.write_text(wanted, encoding="utf-8")

    if not stale:
        print("docs/generated is current")
        return 0
    if args.check:
        print("docs/generated is out of date: " + ", ".join(stale))
        print("run `uv run python scripts/generate_docs.py` to refresh it")
        return 1
    print("regenerated: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
